name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install the latest version of uv and activate the environment
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
      - name: Install the latest version of uv
        run: uv sync
      - name: Clear up disk space
        run: sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
      - name: Clear up disk space
        run: uv clean
      - name: Check remaining diskspace
        run: df -h
      - name: Run test.sh
        run: bash test.sh
      - name: remove venv for more space
        run: rm -rf .venv
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/pbutler/neb-ex2:latest
      - name: Push Docker image
        run: docker push ghcr.io/pbutler/neb-ex2:latest
