name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Clear up disk space
      run:  sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
    - name: Check remaining diskspace
      run: df -h
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag neb-ex2:$(date +%s)
